[2021-10-31 23:59:44,418] {processor.py:163} INFO - Started process (PID=75) to work on /opt/airflow/dags/sensor_dag.py
[2021-10-31 23:59:44,452] {processor.py:620} INFO - Processing file /opt/airflow/dags/sensor_dag.py for tasks to queue
[2021-10-31 23:59:44,454] {logging_mixin.py:109} INFO - [2021-10-31 23:59:44,453] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/sensor_dag.py
[2021-10-31 23:59:44,992] {logging_mixin.py:109} INFO - [2021-10-31 23:59:44,955] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/sensor_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/sensor_dag.py", line 13, in <module>
    with DAG('dag_sensor', schedule_interval='@daily', start_date=datetime, default_args = default_args, catchup=False) as dag:
NameError: name 'DAG' is not defined
[2021-10-31 23:59:45,576] {processor.py:634} WARNING - No viable dags retrieved from /opt/airflow/dags/sensor_dag.py
[2021-10-31 23:59:45,753] {processor.py:171} INFO - Processing /opt/airflow/dags/sensor_dag.py took 1.413 seconds
